version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
#image: Ubuntu2004 #Sql server (2017) is uncontactable with the connectionstring below (it works on other build environments), issue raised: https://github.com/appveyor/website/issues/786
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Vcdb_SqlServer_ConnectionString: server=(local)\SQL2017;User ID=sa;Password=Password12!
  Vcdb_SqlServer_UseLocalDatabase: true
  Vcdb_MySql_ConnectionString: server=localhost;uid=root;pwd=Password12!
  Vcdb_MySql_UseLocalDatabase: true
  Vcdb_MySql_Version: "5.7.33"
  Vcdb_SqlServer_Version: "2017"
services: 
- mssql2017
- mysql
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: dotnet restore
build:
  project: vcdb.sln
  verbosity: minimal
on_failure:
- cmd: 7z a TestResults-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\TestScenarios\**\*.*
- cmd: appveyor PushArtifact TestResults-%APPVEYOR_BUILD_VERSION%.zip
