services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: vcdb_2020
    ports:
      - "1433:1433"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: vcdb_2020
    ports:
     - "3306:3306"