ALTER USER [MyUser]
WITH DEFAULT_SCHEMA = [MySchema],
LOGIN = [MyOtherLogin_Change]
GO
ALTER USER [MyEnabledUser]
WITH DEFAULT_SCHEMA = [dbo]
GO
ALTER LOGIN [MyEnabledLogin]
DISABLE
GO
ALTER LOGIN [MyDisabledLogin]
ENABLE
GO
