DROP USER [MyUser]
GO
CREATE USER [MyUser] FOR LOGIN [MyOtherLogin_Change]
GO
ALTER USER [MyUser]
WITH DEFAULT_SCHEMA = [MySchema]
GO
ALTER USER [MyEnabledUser]
WITH DEFAULT_SCHEMA = [dbo]
GO
ALTER LOGIN [MyEnabledLogin]
DISABLE
GO
ALTER LOGIN [MyDisabledLogin]
ENABLE
GO
