DENY CONTROL ON SCHEMA :: [MySchema] TO [MyUser_Deny] CASCADE
GO
GRANT CONTROL ON SCHEMA :: [MySchema] TO [MyUser_Grant] WITH GRANT OPTION
GO
REVOKE CONTROL ON SCHEMA :: [MySchema] TO [MyUser_Change] CASCADE
GO
GRANT CONTROL ON SCHEMA :: [MySchema] TO [MyUser_Change]
GO
